
server:
  servlet:
    context-path: /demo
  port: '9091'

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /manage
  endpoint:
    health:
      group:
        custom:
          include: diskSpace,ping
          show-components: always
          show-details: always
spring:
  rabbitmq:
    password: admin
    port: '15672'
    host: 127.0.0.1
    username: admin
  data:
    mongodb:
      port: '27017'
      host: localhost
      database: BookStore

